[package]
name = "smcp-server-hyper"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "A2C-SMCP Server Hyper HTTP adapter"
repository = "https://github.com/A2C-SMCP/rust-sdk"
keywords = ["smcp", "server", "hyper", "http"]
categories = ["network-programming", "web-programming"]

[dependencies]
smcp-server-core.workspace = true

tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

hyper.workspace = true
hyper-util.workspace = true
http-body-util.workspace = true
socketioxide.workspace = true
tower.workspace = true

[dev-dependencies]
smcp.workspace = true
reqwest.workspace = true
tf-rust-socketio = { workspace = true }
serde_json = { workspace = true }
futures.workspace = true
async-trait.workspace = true
http.workspace = true
